### ISSUE TITLE
Investigate possibility of not create load-balancers in aws/cloud.Service

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-cloud#634] opened 2018-10-22 22:37 UTC
Reported by @danny-waite

**Comment by joeduffy** [comment] 2018-10-30 22:00
Is this the same as https://github.com/pulumi/pulumi-cloud/issues/633?

**Comment by lukehoban** [comment] 2018-10-30 23:54
This is actually more or less a duplicate of https://github.com/pulumi/pulumi-cloud/issues/441.  (Indeed, the ask for this from @danny-waite was if I recall so that he could implement #441 himself).  I'm not sure it's "correct" to not emit a load balancer for an exposed port until we support some form of service discovery to be able to reference the exposed port.

**Closed by lukehoban** 2018-10-30 23:54 UTC
